fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: i.ovidiuenache@gmail.com
        sender_name: IZINT | Reset Password Request
    service:
        mailer: fos_user.mailer.twig_swift
