framework:
    secret: '%env(APP_SECRET)%'
    default_locale: "en"
    csrf_protection: ~
    #http_method_override: true
    translator: { fallbacks: ["en"] }
    session:
       handler_id: session.handler.native_file
       save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    templating:
       engines: ['twig']

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
