framework:
    secret: '%env(APP_SECRET)%'
    default_locale: "en"
    csrf_protection: ~
    translator: { fallback: '%locale%' }
    session:
       handler_id: session.handler.native_file
       save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    templating:
       engines: ['twig']
    php_errors:
        log: true
