imports:
    - { resource: services/repositories.yaml }
    - { resource: services/mailers.yaml }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    fos_user.security.controller:
        class: App\Controller\SecurityController
