imports:
    - { resource: services/repositories.yaml }
    - { resource: services/mailers.yaml }

parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    fos_user.security.controller:
        class: App\Controller\SecurityController
